name: Generate snake game

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate snake.svg
        uses: Sutil/snk@master  # Keeping your version
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: '#196AFF'  
          background_color: '#0d1117'  
          grid_color: '#30363d' 
          years: 1  # Ensures only past 12 months are used

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Updated version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
